/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package emilyshop.appv2.Vista;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class LoginVista extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    
    
    public LoginVista() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelRound1 = new emilyshop.appv2.Vista.PanelRound();
        lbllogin = new javax.swing.JLabel();
        txtloginusuario = new javax.swing.JTextField();
        btnlogininiciar = new javax.swing.JButton();
        lblusuario = new javax.swing.JLabel();
        lblcontrasena = new javax.swing.JLabel();
        lblregistro = new javax.swing.JLabel();
        btnloginregistrar = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        txtfondologin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setBackground(new java.awt.Color(204, 208, 207,100));
        panelRound1.setRoundBottomLeft(40);
        panelRound1.setRoundBottomRight(40);
        panelRound1.setRoundTopLeft(40);
        panelRound1.setRoundTopRight(40);

        lbllogin.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lbllogin.setForeground(new java.awt.Color(255, 255, 255));
        lbllogin.setText("Login");

        txtloginusuario.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        txtloginusuario.setForeground(new java.awt.Color(40, 40, 40));
        txtloginusuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtloginusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtloginusuarioActionPerformed(evt);
            }
        });

        btnlogininiciar.setText("Iniciar Sesion");
        btnlogininiciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogininiciarActionPerformed(evt);
            }
        });

        lblusuario.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblusuario.setForeground(new java.awt.Color(255, 255, 255));
        lblusuario.setText("Usuario");

        lblcontrasena.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblcontrasena.setForeground(new java.awt.Color(255, 255, 255));
        lblcontrasena.setText("Contraseña");

        lblregistro.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblregistro.setForeground(new java.awt.Color(255, 255, 255));
        lblregistro.setText("------------------Registrate aqui---------------------");

        btnloginregistrar.setText("Registrar");
        btnloginregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginregistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(lbllogin))
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(btnlogininiciar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblregistro)
                            .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblusuario)
                                .addComponent(txtloginusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblcontrasena)
                                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(btnloginregistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbllogin)
                .addGap(17, 17, 17)
                .addComponent(lblusuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtloginusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblcontrasena)
                .addGap(18, 18, 18)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnlogininiciar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblregistro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnloginregistrar)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel1.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 320, 370));

        txtfondologin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emilyshop/appv2/Recursos/fondologin.jpg"))); // NOI18N
        jPanel1.add(txtfondologin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlogininiciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogininiciarActionPerformed
        String usuario = txtloginusuario.getText();
        String contraseña = jPasswordField1.getText();
        if(usuario.equals("admin") && contraseña.equals("123")){
            InicioVista ventanainicio = new InicioVista();
            ventanainicio.setVisible(true);
            this.dispose();
            ventanainicio.setLocationRelativeTo(null);
        }else{
            JOptionPane.showMessageDialog(null,"Usario o contraseña incorrectos");
        }
    }//GEN-LAST:event_btnlogininiciarActionPerformed

    private void txtloginusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtloginusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtloginusuarioActionPerformed

    private void btnloginregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginregistrarActionPerformed
        
        RegistroVista ventanaregistro = new RegistroVista();
        ventanaregistro.setVisible(true);
        ventanaregistro.setLocationRelativeTo(null);
        this.dispose();
        ventanaregistro.setLocationRelativeTo(null);
        
        
    }//GEN-LAST:event_btnloginregistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogininiciar;
    private javax.swing.JButton btnloginregistrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel lblcontrasena;
    private javax.swing.JLabel lbllogin;
    private javax.swing.JLabel lblregistro;
    private javax.swing.JLabel lblusuario;
    private emilyshop.appv2.Vista.PanelRound panelRound1;
    private javax.swing.JLabel txtfondologin;
    private javax.swing.JTextField txtloginusuario;
    // End of variables declaration//GEN-END:variables
}
